# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 849b0a44abbb8e7656c59778478b98f8da77a99e5e7b501fa0c22e9c6fa66c0b0729953bb07045dcdbb66ad7f7881ba9de5636eed1a0d9bf7bea7cc1255d97f6

test:
  secret_key_base: e14625400bed899712f096be8e45b2d436bf6703927c3f786bd7e2daa9ea69b0009503590c86eb4d358b95428172766f2ecf47761edca001ed33fcff5a74c91a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
